Repository chingu-voyages/V54-tier1-team-01, pull requests merged in 2025-04, with the labels that each got.

#69 Added ScenarioSection component with markdown rendering
  client/src/components/MainComponent.jsx
  client/src/components/ScenarioSection.jsx
  client/src/js/apis/geminiAPI.js
Labels: must_have, fe, first prior

#70 feature:gemini-styling: gemini style files; changes; added to Scenario section
  client/src/App.css
  client/src/components/MainComponent.jsx
  client/src/components/ScenarioSection.jsx
  client/src/style/MainComponent.css
Labels: enhancement, nice_to_have, fe

#72 tech:firebase-hosting: configuring for firebase hosting
  client/.firebase/hosting.ZGlzdA.cache
  client/.firebaserc
  client/firebase.json
  client/spikes/geminiAPI/curl-requests-tests.markdown
Labels: technical

#74 feature:ec-#55: --several lines -- added result section component;
  client/src/components/MainComponent.jsx
  client/src/components/ResultSection.jsx
  client/src/data/geminiPromptDescriptionInfo.js
Labels: fe

#75 Feature/ec #59 resultsection functionality
  client/src/components/InputSection.jsx
  client/src/components/MainComponent.jsx
  client/src/components/ResultSection.jsx
  client/src/data/geminiPromptDescriptionInfo.js
Labels: fe

#77 fix:improv-prompt: modif prompt to get tips about each component of t…
  client/src/components/ScenarioSection.jsx
  client/src/data/geminiPromptDescriptionInfo.js
Labels: fe, fix

#80 doc:readme: definitive content last sprint
  README.md
Labels: documentation

#81 doc:readme: add working URL
  README.md
Labels: documentation
